redis:
  auth:
    enabled: false
  replica:
    replicaCount: 1
    persistence:
      enabled: false
  master:
    disableCommands: []
    persistence:
      enabled: false

postgresql:
  persistence:
    size: 16Gi
  resources:
    limits:
      memory: 2Gi